### Get Customer Account Access Token
POST http://localhost:8000/api/token/ HTTP/1.1
Host: localhost:8000
Content-Type: application/json

{
    "username": "customer1",
    "password": "pass1234"
}


### Get Order
GET http://localhost:8000/orders/ HTTP/1.1
Host: localhost:8000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU1MjUwNzkwLCJpYXQiOjE3NTUyNDcxOTAsImp0aSI6IjUxN2YwZGI3ODA4NjQyYzJhZTYzZWEzYTE1ZmVlODc4IiwidXNlcl9pZCI6IjUifQ.Phtj6rBxS61oA-kylkrcyi-p1k5UrOnmfDLC0icWYF4

### Create an Order
POST http://localhost:8000/orders/ HTTP/1.1
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU1MjU3ODIyLCJpYXQiOjE3NTUyNTQyMjIsImp0aSI6IjllZjIxOTQ5Y2RiYTRjODc4NDAyZTM5MWMwZmZmYWJmIiwidXNlcl9pZCI6IjUifQ.WrCLZ1IV8x4G5_buNZhL5rdmRUboxyWbLMxVr59yfKo

{
  "restaurant": 2,
  "status": "pending",
  "items": [
    { "menu_item": 3, "quantity": 2 },
    { "menu_item": 4, "qutiy": 1 }
  ]
}

### Get an Order
GET http://localhost:8000/orders/9a8d34ba-fef2-4511-a089-1963cdd77082/ HTTP/1.1
Host: localhost:8000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU1MjUwNzkwLCJpYXQiOjE3NTUyNDcxOTAsImp0aSI6IjUxN2YwZGI3ODA4NjQyYzJhZTYzZWEzYTE1ZmVlODc4IiwidXNlcl9pZCI6IjUifQ.Phtj6rBxS61oA-kylkrcyi-p1k5UrOnmfDLC0icWYF4


### Update an Order
PUT http://localhost:8000/orders/9a8d34ba-fef2-4511-a089-1963cdd77082/ HTTP/1.1
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU1MjUwNzkwLCJpYXQiOjE3NTUyNDcxOTAsImp0aSI6IjUxN2YwZGI3ODA4NjQyYzJhZTYzZWEzYTE1ZmVlODc4IiwidXNlcl9pZCI6IjUifQ.Phtj6rBxS61oA-kylkrcyi-p1k5UrOnmfDLC0icWYF4

{
  "restaurant": 2,
  "items": [
    { "menu_item": 3, "quantity": 2 },
    { "menu_item": 4, "quantity": 10 }
  ]
}

### Get Reviews
GET http://localhost:8000/reviews/ HTTP/1.1
Host: localhost:8000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU1MjUwNzkwLCJpYXQiOjE3NTUyNDcxOTAsImp0aSI6IjUxN2YwZGI3ODA4NjQyYzJhZTYzZWEzYTE1ZmVlODc4IiwidXNlcl9pZCI6IjUifQ.Phtj6rBxS61oA-kylkrcyi-p1k5UrOnmfDLC0icWYF4

### Get 1 Reviews
GET http://localhost:8000/reviews/2/ HTTP/1.1
Host: localhost:8000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU1MjUwNzkwLCJpYXQiOjE3NTUyNDcxOTAsImp0aSI6IjUxN2YwZGI3ODA4NjQyYzJhZTYzZWEzYTE1ZmVlODc4IiwidXNlcl9pZCI6IjUifQ.Phtj6rBxS61oA-kylkrcyi-p1k5UrOnmfDLC0icWYF4

### Get Reviews
PATCH http://localhost:8000/reviews/2/ HTTP/1.1
Host: localhost:8000
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU1MjUwNzkwLCJpYXQiOjE3NTUyNDcxOTAsImp0aSI6IjUxN2YwZGI3ODA4NjQyYzJhZTYzZWEzYTE1ZmVlODc4IiwidXNlcl9pZCI6IjUifQ.Phtj6rBxS61oA-kylkrcyi-p1k5UrOnmfDLC0icWYF4

{
  "rating": 2
  
}
