### Get Customer Account Access Token
POST http://localhost:8000/api/token/ HTTP/1.1
Host: localhost:8000
Content-Type: application/json

{
    "username": "owner1",
    "password": "pass1234"
}

###

GET http://localhost:8000/menu_item/4/ HTTP/1.1
Host: localhost:8000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU2NDU5NzQ1LCJpYXQiOjE3NTY0NTYxNDUsImp0aSI6IjA1YWE0ZjI0OTRkYjQ3ZTE5YmQyZjRlNGJhYWYyODM5IiwidXNlcl9pZCI6IjQifQ.AiSkpdAXWimPchkz0qd2jK91ugdcxUuTivsvgjsn5tg

##
GET http://localhost:8000/user/5/ HTTP/1.1
Host: localhost:8000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU2NDUzMTcwLCJpYXQiOjE3NTY0NDk1NzAsImp0aSI6ImUyOWI1ODBiZWMxMjQ3NzBiZTgzOWY3MWUwNDVmZWVjIiwidXNlcl9pZCI6IjUifQ.i1jZK-Bl1oko7-2rRCkgaBQSaQ9jWQkfo4JTqJP3WPg

### Get Order
GET http://localhost:8000/orders/ HTTP/1.1
Host: localhost:8000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU2NDM5NTY0LCJpYXQiOjE3NTY0MzU5NjQsImp0aSI6ImRlYjhkMmEwMjNiNjQyODlhN2RjYTllMzVhMTAxMDIxIiwidXNlcl9pZCI6IjUifQ.cdqa16CXQmj2gMC8B3YiMpG0gRzSXLR-nXA44929_h8
### Create an Order
POST http://localhost:8000/orders/ HTTP/1.1
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU1MjU3ODIyLCJpYXQiOjE3NTUyNTQyMjIsImp0aSI6IjllZjIxOTQ5Y2RiYTRjODc4NDAyZTM5MWMwZmZmYWJmIiwidXNlcl9pZCI6IjUifQ.WrCLZ1IV8x4G5_buNZhL5rdmRUboxyWbLMxVr59yfKo

{
  "restaurant": 2,
  "status": "pending",
  "items": [
    { "menu_item": 3, "quantity": 2 },
    { "menu_item": 4, "qutiy": 1 }
  ]
}

### Get an Order
GET http://localhost:8000/orders/9a8d34ba-fef2-4511-a089-1963cdd77082/ HTTP/1.1
Host: localhost:8000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU1MjUwNzkwLCJpYXQiOjE3NTUyNDcxOTAsImp0aSI6IjUxN2YwZGI3ODA4NjQyYzJhZTYzZWEzYTE1ZmVlODc4IiwidXNlcl9pZCI6IjUifQ.Phtj6rBxS61oA-kylkrcyi-p1k5UrOnmfDLC0icWYF4


### Update an Order
PUT http://localhost:8000/orders/9a8d34ba-fef2-4511-a089-1963cdd77082/ HTTP/1.1
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU1MjUwNzkwLCJpYXQiOjE3NTUyNDcxOTAsImp0aSI6IjUxN2YwZGI3ODA4NjQyYzJhZTYzZWEzYTE1ZmVlODc4IiwidXNlcl9pZCI6IjUifQ.Phtj6rBxS61oA-kylkrcyi-p1k5UrOnmfDLC0icWYF4

{
  "restaurant": 2,
  "items": [
    { "menu_item": 3, "quantity": 2 },
    { "menu_item": 4, "quantity": 10 }
  ]
}

### Get Reviews
GET http://localhost:8000/reviews/ HTTP/1.1
Host: localhost:8000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU1MjUwNzkwLCJpYXQiOjE3NTUyNDcxOTAsImp0aSI6IjUxN2YwZGI3ODA4NjQyYzJhZTYzZWEzYTE1ZmVlODc4IiwidXNlcl9pZCI6IjUifQ.Phtj6rBxS61oA-kylkrcyi-p1k5UrOnmfDLC0icWYF4

### Get 1 Reviews
GET http://localhost:8000/reviews/2/ HTTP/1.1
Host: localhost:8000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU1MjUwNzkwLCJpYXQiOjE3NTUyNDcxOTAsImp0aSI6IjUxN2YwZGI3ODA4NjQyYzJhZTYzZWEzYTE1ZmVlODc4IiwidXNlcl9pZCI6IjUifQ.Phtj6rBxS61oA-kylkrcyi-p1k5UrOnmfDLC0icWYF4

### Get Reviews
PATCH http://localhost:8000/reviews/2/ HTTP/1.1
Host: localhost:8000
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU1MjUwNzkwLCJpYXQiOjE3NTUyNDcxOTAsImp0aSI6IjUxN2YwZGI3ODA4NjQyYzJhZTYzZWEzYTE1ZmVlODc4IiwidXNlcl9pZCI6IjUifQ.Phtj6rBxS61oA-kylkrcyi-p1k5UrOnmfDLC0icWYF4

{
  "rating": 2
  
}
