# Generated by Django 5.1.1 on 2025-08-29 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['restaurant_id']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['restaurant_id']},
        ),
    ]
